In [1]:
import pandas as pd
import pynbody as pyn
import matplotlib.pyplot as plt
import numpy as np
from scipy.optimize import curve_fit
from scipy import optimize
from astropy import units as unit
import sys
import os 
import pickle
import funciones as fn
import statistics as stats
from tabulate import tabulate

In [2]:
data_nuevo = '/media/danna01/Disk/SNAPSHOTS/Galaxias_Nuevas'
data_viejo = '/media/danna01/Disk/SNAPSHOTS/Galaxias_Viejas'

In [3]:
data_newg0 = pyn.load(data_nuevo +'/G0/snapshot_100.hdf5')
data_oldg0 = pyn.load(data_viejo +'/G0/snapshot_100.hdf5')
data_newg1 = pyn.load(data_nuevo +'/G1/snapshot_100.hdf5')
data_oldg1 = pyn.load(data_viejo +'/G1/snapshot_100.hdf5')
data_newg2 = pyn.load(data_nuevo +'/G2/snapshot_100.hdf5')
data_newg3 = pyn.load(data_nuevo +'/G3/snapshot_100.hdf5')

/home/danna01/.local/lib/python3.8/site-packages/pynbody/snapshot/gadgethdf.py:508: RuntimeWarning: No unit information found!
  warnings.warn("No unit information found!", RuntimeWarning)
/home/danna01/.local/lib/python3.8/site-packages/pynbody/snapshot/gadgethdf.py:572: RuntimeWarning: No unit information found: using gadget-units.
  warnings.warn(

In [4]:
file = open('diccionarios_nuevos/compilation_new', 'rb')
super_dict = pickle.load(file)
file.close()

file = open('diccionarios_nuevos/compilation_old', 'rb')
super_dict_old = pickle.load(file)
file.close()
#Estas lineas que se agregan son necesarias porque el diccionario no tiene la informacion requerida para las 
#galaxias G2 y G3, por ende, se agregan como diccionarios vacios para no generar un error a la hora de aplicar
#la funcion de graficas.
super_dict_old['G2']={} 
super_dict_old['G3']={}

In [5]:
def extract_qtt(dictionary,quantity):
    if quantity == 'snapshots':
        lista = [np.float(key) for key in dictionary.keys()]
    else:
        # list comprehensionlimits
        lista = [dictionary[snap][quantity] for snap in dictionary.keys()]
    return lista

In [6]:
masa_barionica_total_newg0 = data_newg0.star['mass'].sum() + data_newg0.gas['mass'].sum()
masa_total_newg0 = data_newg0.star['mass'].sum() + data_newg0.gas['mass'].sum() +  data_newg0.dm['mass'].sum()
masa_barionica_total_oldg0 = data_oldg0.star['mass'].sum() + data_oldg0.gas['mass'].sum()
masa_total_oldg0 = data_oldg0.star['mass'].sum() + data_oldg0.gas['mass'].sum() +  data_oldg0.dm['mass'].sum()

masa_barionica_total_newg1 = data_newg1.star['mass'].sum() + data_newg1.gas['mass'].sum()
masa_total_newg1 = data_newg1.star['mass'].sum() + data_newg1.gas['mass'].sum() +  data_newg1.dm['mass'].sum()
masa_barionica_total_oldg1 = data_oldg1.star['mass'].sum() + data_oldg1.gas['mass'].sum()
masa_total_oldg1 = data_oldg1.star['mass'].sum() + data_oldg1.gas['mass'].sum() +  data_oldg1.dm['mass'].sum()

masa_barionica_total_newg2 = data_newg2.star['mass'].sum() + data_newg2.gas['mass'].sum()
masa_total_newg2 = data_newg2.star['mass'].sum() + data_newg2.gas['mass'].sum() +  data_newg2.dm['mass'].sum()

masa_barionica_total_newg3 = data_newg3.star['mass'].sum() + data_newg3.gas['mass'].sum()
masa_total_newg3 = data_newg3.star['mass'].sum() + data_newg3.gas['mass'].sum() +  data_newg3.dm['mass'].sum()

In [7]:
data = pd.DataFrame({"Galaxies": [" ","G0", "G1", "G2", "G3"],
                     
                     '': ['Paper','5.1','20','51','116'],
                     
                     'Total Mass [$10^{10}$ $M_\odot$]': ['New Simulations',masa_total_newg0,masa_total_newg1,
                                                            masa_total_newg2,masa_total_newg3],
                     
                     ' ': ['Old Simulations',masa_total_oldg0,masa_total_oldg1,'',''],
                     
                     '  ': ['Paper','0.16','0.7','1.98','6.22'],
                     
                     'Baryonic Mass [$10^{10}$ $M_\odot$]': ['New Simulations',masa_barionica_total_newg0,
                                                                masa_barionica_total_newg1,masa_barionica_total_newg2,
                                                                masa_barionica_total_newg3],
                     
                     '   ': ['Old Simulations',masa_barionica_total_oldg0,masa_barionica_total_oldg1,'',''],
                     
                     '    ': ['Paper','0.06','0.2','0.45','1.24'],
                     
                     'Gas Mass [$10^{10}$ $M_\odot$]': ['New Simulations',data_newg0.gas['mass'].sum(),
                                                          data_newg1.gas['mass'].sum(),data_newg2.gas['mass'].sum(),
                                                          data_newg3.gas['mass'].sum()],
                     
                     '     ': ['Old Simulations',data_oldg0.gas['mass'].sum(),data_oldg1.gas['mass'].sum(),'',''],
                    })
data.style.set_properties(**{'text-align': 'center'})

In [14]:
data = pd.DataFrame({"Galaxies": [" ","G0", "G1", "G2", "G3"],
                     
                     '': ['Paper','1.1','1.5','1.9','2.8'],
                     
                     'Scalelength Star [kpc]': ['New Simulations',stats.median(extract_qtt(super_dict["G0"],'h_star')), 
                                                 stats.median(extract_qtt(super_dict["G1"],'h_star')), 
                                                 stats.median(extract_qtt(super_dict["G2"],'h_star')), 
                                                 stats.median(extract_qtt(super_dict["G3"],'h_star'))],
                     
                     ' ': ['Old Simulations',stats.mean(extract_qtt(super_dict_old["G0"],'h_star')),
                           stats.mean(extract_qtt(super_dict_old["G1"],'h_star')),'',''],
                     
                     '  ': ['Paper','3.3','4.5','5.7','8.4'],
                     
                     'Scalelength Gas [kpc]': ['New Simulations',stats.median(extract_qtt(super_dict["G0"],'h_gas')), 
                                                stats.median(extract_qtt(super_dict["G1"],'h_gas')), 
                                                stats.median(extract_qtt(super_dict["G2"],'h_gas')), 
                                                stats.median(extract_qtt(super_dict["G3"],'h_gas'))],
                     
                     '   ': ['Old Simulations',stats.mean(extract_qtt(super_dict_old["G0"],'h_gas')), 
                             stats.mean(extract_qtt(super_dict_old["G1"],'h_gas')),'',''],
                     
                     '    ': ['Paper','67','103','139','192'],
                     
                     'V max [km s$^{-1}$]': ['New Simulations',stats.median(extract_qtt(super_dict["G0"],'Vmax')), 
                                             stats.median(extract_qtt(super_dict["G1"],'Vmax')), 
                                             stats.median(extract_qtt(super_dict["G2"],'Vmax')), 
                                             stats.median(extract_qtt(super_dict["G3"],'Vmax'))],
                     
                     '     ': ['Old Simulations',stats.mean(extract_qtt(super_dict_old["G0"],'Vmax')),
                               stats.mean(extract_qtt(super_dict_old["G1"],'Vmax')),'','']
                    })
data.style.set_properties(**{'text-align': 'center'})